### ISSUE TITLE
LANDING PAGE MAP ERRORS ON NES GRANT LINKS 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#101]
Very critical as we are sending out links to members this week!

All NES grant links are broken. NES Mongolia and Tanzania are not displaying other info, how can we fix this? both have facilitators in NES facilitators list albeit these might not be the same as host org. please let me know how to proceed. thanks 
![bugonmap](https://user-images.githubusercontent.com/40179449/64241866-cd23b900-cf04-11e9-8d02-eafd302725b0.JPG)

**Comment by IronRunes** [comment]
This is fixed, also added a forced reload of the cached files to make sure it is working as wanted

**Comment by decasadecasa** [comment]
Thanks, the links work now. Any advice on how to make the rest of the info display for pop up boxes NES Mongolia & Tanzania?
