### ISSUE TITLE
Request new account linked to mnet email not working 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#102]
we have received several requests for a new account, but the email we get only has a link, such as the following:

https://mnet-dev.landcoalition.org/user/edit/313

once i open it, the following screen appears. Where do we go from here? how do we know who to make the account for? 

![Capture](https://user-images.githubusercontent.com/40179449/64438452-6949ed80-d0c8-11e9-9d1a-a56f4e0cfa59.JPG)

**Comment by IronRunes** [comment]
Ok, I managed to take a deeper look. 

I think that the link above pointed you to an account request made by the Slowfood people, account that we removed as it was meddling with the account you created for them. 

If you click on the other links that point to other account requests, you'll find the data in the forms. 

I'll close this as there is no action take from the technical point of view.
