### ISSUE TITLE
Mnet - Manage Grants section not responding

### ISSUE THREAD

**Issue by Derrd** [level73/membernet#104]
I was trying to upload a document (annex) on Mnet - manage grants section - but it seems the system doesn't let me upload the file. It doesn't upload meaning that I click save and the page is charging and uploading but then the file disappears.

**Comment by IronRunes** [comment]
Hey @Derrd , questions: 
1. What kind of file is it? (doc, pdf, image, spreadsheet...)
2. How large is the file, in terms of Megabytes?

thanks
alan

**Comment by Derrd** [comment]
they are both pdf
![2](https://user-images.githubusercontent.com/54991948/64687813-7af61100-d48b-11e9-9e45-424e8bafb78f.PNG)

**Comment by Derrd** [comment]
annex 5 and 6

**Comment by Derrd** [comment]
maybe too heavy?

**Comment by IronRunes** [comment]
> maybe too heavy?

yes, I'd say that's the problem. I can find a workaround, but it's the first time I see such a large attachment to Mnet

**Comment by Derrd** [comment]
I see. may I ask what are the implications of increasing the permitted file size? if any 
So looking forward to your kind reply to upload the documents.

Thank you again!
