### ISSUE TITLE
landing page map: switch ILC office filter to tick in order to turn on, not off

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#110]
as its hard to view the nes and cbis where there are also ilc offices, please make the box so that only upon clicking it will the flags show up, instead of vice versa.

**Comment by decasadecasa** [comment]
i meant that the flags dont display automatically, but upon ticking the box. the change you made leaves the flag on, but just changed the wording to now incorrectly state, show instead of hide. please make flags only appear after user clicks box entitled, view ILC Regional Coordination Units

**Comment by IronRunes** [comment]
CTRL + F5 ;)
