### ISSUE TITLE
good practices not linking to Platformpage

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#116]
for NES ALBANIA we have a good practice, but i dont know whether its not showing up on the front because im missing some tag, or because they are not synched. I tagged the country and everything in the back end in manage good practices but perhaps we need to add the platform tag to the back end of that entity as well? please let me know. thanks

**Comment by IronRunes** [comment]
@decasadecasa added the platform meta layer to good practices

**Comment by IronRunes** [comment]
@decasadecasa have you tested this out by any chance? that way I can close the issue

**Comment by decasadecasa** [comment]
it works. thanks
