### ISSUE TITLE
FINDME contact role sync

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#117]
![findme](https://user-images.githubusercontent.com/40179449/70991475-ce4db000-20c7-11ea-86f5-23ba94a35392.PNG)

I switched a contact from an alternate fp to fp and now it is showing up as both.
furthermore in FINDME i cant find the same contact by only searching for the surname (LOFTI) whereas it does work with first name (AMINA).

**Comment by IronRunes** [comment]
Quick note on this: the surname is "LOTFI" and the search returns it successfully

I'll check the role sync, but we already have this at hand with the new roles for findme to debug

I'll close this one
