### ISSUE TITLE
Arrange staff list on ONETEAM alphabetically, by region

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#129]

**Comment by decasadecasa** [comment]
@IronRunes please address this today, if possible

**Comment by IronRunes** [comment]
@decasadecasa I think this would apply only for regional groupings, while the general "main" contacts are already sorted as desired?

**Comment by decasadecasa** [comment]
in regional yes ( and the changes are not showing for me, despite a hard refresh)
for the main contacts keep as is for now.

**Comment by decasadecasa** [comment]
ah, you arranged it alphabetically by last name. i see. that is fine. please do the same for the main contacts (we had complaints about the ratio of men to women so this will bring zulema to the front) thanks
