### ISSUE TITLE
Only Alan can edit NES/CBI Focal points currently.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#13]
The section is not editable by other authorized users.

**Comment by IronRunes** [comment]
I added 2 new roles for contacts: 

- NES Focal Point
- CBI Focal Point

Do you think this is enough? We can tag contacts by Work Area, so to enhance the details around their role as Platform Focal Points, and we can also expand to initiatives (would need to add that to the meta layer for contacts, but it's feasable). 

Let me know :)

**Comment by decasadecasa** [comment]
Would the workarea/initiative layer appear in all contact entry forms? I wouldnt want them to be so crowded with options. Would it be possible to just have NES/CBI focal point, and then an area where we could just write what their specific role is (like a blank fill-in section)? Hope that makes sense. Thanks!

**Comment by IronRunes** [comment]
we can do that, but the specific role info would need to be on the first entry form (the entity-specific stuff). We could name it something along the lines of "Other Info", and then display it only for NES/CBI Focal Points

**Comment by decasadecasa** [comment]
Sounds good! Thanks

**Comment by IronRunes** [comment]
I added the field in the backend (Manage -> Manage Contacts)
Let me know when we have data in there, and the NES/CBI Focal points have been tagged, so we can move forward to displaying that information on the frontend. :)

**Comment by decasadecasa** [comment]
Hi @IronRunes, we have updated the NES/CBI focal points, including their respective facilities in the "other information" field. Please let us know how to move forward with this! Thanks :)

**Comment by IronRunes** [comment]
Done and done
