### ISSUE TITLE
Hide ILC pages

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#130]
Please hide:
1) ILC pages from member list 
2) Filter to view ILC pages on member list
3) From search drop down list
4) On landing page, if signed in with ONETEAM account, either hide"view your profile" button

**Comment by IronRunes** [comment]
- [ ] hidden from member list
- [ ] hidden the filter in the member list
- [ ] hidden entries from search drop down in member list
- [ ] removed "your profile" button and swapped with "ONE TEAM" button on dashboard if user is ONE TEAM member
