### ISSUE TITLE
Replace KILIMANJARO INITIATIVE (CBI) wtih Women's Land Rights in Africa

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#134]
Please keep is so that past things that are tagged under Kilimanjaro stay as such, but for new ones we have to change the name to Women's Land Rights in Africa. applies to both front and back end 

Let me know if that makes sense or presents problems. thanks

**Comment by IronRunes** [comment]
This is problematic. We can either change all over the application or create a new platform with the new name. let me know how we should go about it.

**Comment by decasadecasa** [comment]
New platforms with new name. Thanks

**Comment by IronRunes** [comment]
Done.
