### ISSUE TITLE
Add FACILITIES to back-end tags

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#138]
Please add the following list under FACILITIES (for now just in back-end, until we define the page):

•	Alternative Reporting
•	Community Land Protection
•	Gender Audit 
•	Good Governance 
•	Internship 
•	Land in SDGs
•	Land Rights Now  
•	LANDex 
•	Landmark
•	Large Scale Land Acquisitions & Land Grabbing 
•	LED Emergency Fund 
•	Legal Redress Mechanism 
•	Tools for Securing Land Rights
•	Women to Women Mentoring
•	Youth and Leadership

**Comment by IronRunes** [comment]
we already have a list of facility types, does this integrate the existing list or does it substitute it?

**Comment by IronRunes** [comment]
This is completed.
