### ISSUE TITLE
Make ONETEAM page log-in page for ILC STAFF

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#140]

**Comment by IronRunes** [comment]
To make sure this is doable, I need a little context. 
To differentiate between a member (or other) user and ILC Staff, the platform must identify them first - this is usually done via the login process, but we are looking for a way to identify users before this happens. 
This could be done via a check on the referring IP address, or offering a different URL (something like "oneteam.landcoalition.org"), but both have a level of complexity that can either render the job somewhat pointless or have implications during the normal operations to be conducted on the platform.

**Comment by decasadecasa** [comment]
Hi. Sorry, I think I was a bit unclear here. I meant that the staff have the ONETEAM page as the landing page upon logging in, not that it would replace the log-in/credentials page. Would that be doable, since they are all tagged to ILC accounts?
