### ISSUE TITLE
Creating new user account for MemberNet

### ISSUE THREAD

**Issue by ghost** [level73/membernet#146]
Following up from Dunia’s request about giving access to MemberNet and M&E for Hilde van Dijkhorst hdj@mdf.nl.
Yesterday I tried creating an account from the log in page and also tried adding one from the administrator's end through manage users and both did not work.
I tried this process twice.
Even checked with Hilde whether any emails were received regarding this and there were none.

**Comment by IronRunes** [comment]
@decasadecasa I removed the validation check on users needing to be part of a registered org, only in the admin backend (not for user requests). 
I checked if the thing works, and Hilde's profile is now successfully showing up. 
I'll send you her pwd by other means
