### ISSUE TITLE
check disclosure on grant detail page

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#148]
assure that private tags work with all file types, not just TSRs

**Comment by IronRunes** [comment]
Hey @decasadecasa  as far as I see from the code, this works fine - note that ILC staff will always see all documents, as that overrides the disclosure parameter of single files. 
If you have an example (even with a dummy document, so to not potentially expose anything sensitive) we could give it a go.

**Comment by decasadecasa** [comment]
yes this is working. thanks!
