### ISSUE TITLE
No confirmation when deleting elements.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#15]
In Manage entities no deleting confirmation pops up when you want to delete an element.

**Comment by IronRunes** [comment]
hey @exhej11 is this the same as described in issue #2 ?

**Comment by exhej11** [comment]
Yes this is a part of issue number 2 but should be treated separately since it is of a higher importance. Unresponsiveness and small errors of this type also need to be fixed with the delete button

**Comment by IronRunes** [comment]
System now requires confirmation and provides feedback on the success/failure of the operation.
If this is ok, we would also amend issue #2 to reflect the successful changes.

**Comment by decasadecasa** [comment]
I just tested this with a contact and a grant and I did not get prompted for confirmation. Does it take a while to update?

**Comment by IronRunes** [comment]
> I just tested this with a contact and a grant and I did not get prompted for confirmation. Does it take a while to update?

You most probably need a hard refresh (ctrl + F5)

**Comment by decasadecasa** [comment]
yes ,it worked after hard refresh. I did try logging out and in before hand and that didn't work, so is the hard refresh necessary for all users before the function works?

**Comment by IronRunes** [comment]
it should propagate, I can "force" the update though - I'll do that 
can we close this one?
