### ISSUE TITLE
Password recovery not working 

### ISSUE THREAD

**Issue by ghost** [level73/membernet#150]
Password recovery not working for Rosa Montalvo (r.montalvo@landcoalition.info)

**Comment by IronRunes** [comment]
I assume she checked her spam inbox - if she did and the email isn't there I can send her the recovery URL privately while we investigate the issue.

**Comment by decasadecasa** [comment]
She did check the spam.

Ok, please send it to me and I will forward it due to language barriers

**Comment by IronRunes** [comment]
sent to your email

cheers
