### ISSUE TITLE
Missing countries from M&E drop-downs (NEEDS REVIEW, do not execute yet) 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#152]
Please add the following countries to the M&E drop-down menus:

in Africa:
-Liberia
-South Sudan

in EMENA:
-Moldova
-Kosovo
-Spain
-Morocco
-Netherlands
-Scotland
-Jordan
-Palestine

**Comment by IronRunes** [comment]
these are generated by reports tagged accordingly - so if we have reports tagged in Scotland, Scotland should show up in the drop down menu. If this isn't happening, then there's a bug somewhere, otherwise it's the expected behaviour

**Comment by decasadecasa** [comment]
Hi. So this appears to not be working. we have reports tagged for moldova, for example, and it is not generating the tag in the drop down menu.

**Comment by IronRunes** [comment]
I have found 0 NES/CBI Reports connected to Moldova in the database, same goes for other countries like Liberia, South Sudan, Jordan. Are we referring to the same dataset (as in, NES/CBI Reports)?

**Comment by decasadecasa** [comment]
OK, tested Moldova and it does appear, but under global. can you please regroup the following "global" countries, to go under EMENA? 

Spain
Italy
Albania
Kosovo
Morocco
Moldova
Jordan
Palestine

**Comment by IronRunes** [comment]
you can reassign regions from the Metadata layer manager (active for countries only)
