### ISSUE TITLE
Running query for duplicate contacts 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#155]
would it be possible to run a query to find contact duplicates in findme and mnet? so we can delete and clean up?

**Comment by IronRunes** [comment]
based on what parameters? email, name and surname?

**Comment by decasadecasa** [comment]
can you advise here? if we do all 3, im sure we will miss some duplicates.... maybe just name and surname? or is that not a good approach?

**Comment by IronRunes** [comment]
tipically I'd use emails, because there is always the chance of homonymy. I'm about to send an export of the query by email.
