### ISSUE TITLE
Download Excel data from prev cycle and current cycle

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#158]

**Comment by IronRunes** [comment]
@Duniamen I'm including tagged orgs, platforms and countries. Is there any other specific meta layer that you'd need in the final export?

**Comment by Duniamen** [comment]
for this one time i actually wanted the raw data... meaning ALL of it. Equal to what we had done already in the past. let me know if too complicated now, and I will chose info i need.

**Comment by IronRunes** [comment]
all the metadata then. k

**Comment by Duniamen** [comment]
Merci

**Comment by decasadecasa** [comment]
@IronRunes 

Ciao Alan, 
The file is unreadable, as it is it seems info is missing. 
I expected to have the questions in column and the various answers in line.
I would need the expeort for both cycles… 
If downloading the whole raw data is too complicated for now, just please download, the sections for changes in policies/ practices (all 3 fields) the name of the org, the country, the date, the workarea/ platform and commitments int contributes to. 

For the old cycle please 
Download changes in policies, agendas and practices (all fields realted to them) and again the name of the org, the country, the date, the workarea/ platform and commitments int contributes to.
