### ISSUE TITLE
Members' work with ILC section (member profile): separate grants into direct recipient and participant in

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#159]
On member profiles, we want to have 2 separate headings under the X's work with the ILC:
one keeping currently as is with the list of grants that the member was a direct recipient of, and adding another header, under which the grants that the member has been tagged as being part of, will display.

Id need to think of the names for the headings in the meantime. Perhaps this part can replace the gap on the profile now left by the removal of the travels

**Comment by IronRunes** [comment]
@decasadecasa the backend work for this is ready and running. we need the headings to deploy it to the frontend.

**Comment by decasadecasa** [comment]
hi @IronRunes. 

Please keep the work with ILC heading as is, and insert 2 sub-headings.

X is the leading member of the following activities:
X participates in the following activities:

**Comment by IronRunes** [comment]
this is done
