### ISSUE TITLE
Add cycle switcher button for M&E 

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#160]
Adding a cycle switcher button to navigate to previous cycle data

**Comment by IronRunes** [comment]
@Duniamen I addressed this with a cycle-picker element in the M&E Menu. 
Let me know if it works for you. In that case you can close the issue. :)

**Comment by IronRunes** [comment]
@Duniamen we are pending on closing this waiting for the labels in the cycle switcher :) 
the functionality is approved though, right?

**Comment by decasadecasa** [comment]
please change the name of the cycle tab to read "select strategic cycle" and the two buttons as "2015-2018" and "2019-2021"

**Comment by IronRunes** [comment]
Done
