### ISSUE TITLE
FINDME: cant delete contact

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#163]
another case of not being able to delete a contact:

![Capture](https://user-images.githubusercontent.com/40179449/75149148-9aaf8780-5701-11ea-9d19-ddc2949d3941.PNG)

name: Amanda Richardson (16928)

please can we make the error messages more indicative of what the problem so the user might be able to solve the problem themselves?

**Comment by decasadecasa** [comment]
ok, i managed to see that its the same case of the email being linked to the account of resource equity. i tried pasting in a new email and that seemed to work, but still cant delete the contact from findme

**Comment by ghost** [comment]
Unable to delete - 
https://findme.landcoalition.org/contacts/member/17063
https://findme.landcoalition.org/contacts/update/2960
https://findme.landcoalition.org/contacts/member/384

**Comment by IronRunes** [comment]
@kravinthiren @decasadecasa this should be fixed. please remember to follow up deleting on membernet
