### ISSUE TITLE
Unable to unable documents for events

### ISSUE THREAD

**Issue by ghost** [level73/membernet#166]
Unable to upload documents under events.
Tried deleting the event and starting over.
Tried logging out and logging back in and still unable to. 

https://mnet-dev.landcoalition.org/manage/event/98

**Comment by IronRunes** [comment]
hey @kravinthiren could you please share the following bits of info: 
1. Size of the document (in kb or mb)
2. type of file (pdf, docx, xlsx...)

thanks

**Comment by ghost** [comment]
1. 43 MB
2. pdf

**Comment by IronRunes** [comment]
the file is too big to be uploaded - I need to change settings on the server to allow that. 
As soon as that is done I'll let you know

**Comment by IronRunes** [comment]
Bumped up the max file size allowed - should be working now. Let me know so I can close the issue.

**Comment by ghost** [comment]
It works, thanks
