### ISSUE TITLE
Titles not reflecting accurately

### ISSUE THREAD

**Issue by ghost** [level73/membernet#172]
When we upload grants and ICs there is an issue where they are not being named correctly. For example for this IC the title is - A HOTSPOT CASE STUDY ON “1B. EMERGENCE OF BIMODAL AGRICULTURE”, but MemberNet isnt reflecting this.
https://mnet-dev.landcoalition.org/manage/institutionalcontract/169

**Comment by IronRunes** [comment]
the problem here is with the double apex in the title. they will get stripped entirely for security reasons. I have changed the double apex into double quotes and it is now working
