### ISSUE TITLE
NES/CBI reports: adjusting box sizes in manage section

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#173]
in the back end, when adjusting the size of the text box for readability, the % of women and % of youth entry fields do not move with the adjustments, and overlap. 
![M Ebug](https://user-images.githubusercontent.com/40179449/76441846-56d6a680-63c0-11ea-84b1-76a692c2f01f.PNG)

**Comment by IronRunes** [comment]
i fixed this.
