### ISSUE TITLE
NES/CBI Reports: text in italics under each subsection needs its own entry field

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#177]
<img width="949" alt="Screen Shot 2020-03-12 at 12 12 46" src="https://user-images.githubusercontent.com/40179449/76523180-411cbc00-6468-11ea-9ca0-7b6fd63acf09.png">
All text that explains further the field in italics requires its own entry box, as this is a separate question and not just an explanation, and currently this forces us to cramp sections together

**Comment by IronRunes** [comment]
Add extra text field in each of the change stories (2.1, 2.2, 2.3)
