### ISSUE TITLE
Grants and M&E report links

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#180]
in the case of the grant detail page, FUNDAPAZ CBI 1806 (https://mnet-dev.landcoalition.org/detail/grant/646), there is nothing under M&E, even though the report entry on M&E (https://mnet-dev.landcoalition.org/monitor/reporting/57) has been tagged with the correct grant. 

Can you have a look and see what the issue might be? Thanks

**Comment by IronRunes** [comment]
This was happening because we did not include the new cycle in the grant detail view - it is fixed now
