### ISSUE TITLE
NES/CBI Reports: PART 3: Financial update fields and text missing

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#184]
![texthere](https://user-images.githubusercontent.com/40179449/76618516-0038ac00-6529-11ea-8515-e31c36211101.PNG)

**Please insert the following text and fields:** 
INTRO: This financial update provides information on the total resourcing of the NES/CBI, not just the funds provided by ILC. 

**FIELD/BOX**: 3.1 Multi-donor approach to NES/CBI:
Please explain if original financial commitments from other donors and NES/CBI members materialised. (Max. 200 words) &
Please explain major variations from original plans (e.g. fewer funds or more funds due to any fundraising activity). Specify all donors approached, especially if negotiations concluded positively.

**FIELD/BOX**:3.2 Implementation capacity: did you face any financial challenges to implementation? If so, what impact did this have on your plans? (Max. 200 words)
& Please explain if you undertook any measures to increase implementation capacity.

**Comment by IronRunes** [comment]
@decasadecasa are these 4 new boxes to be added to the section, while the main "Description" box stays as is?

**Comment by decasadecasa** [comment]
@IronRunes lets have 3 boxes (replace description):

- 3.1 Multi-donor approach to NES/CBI: please explain if original financial commitments from other donors and NES/CBI members materialised

-(under 3.1) Please explain major variations from original plans (e.g. fewer funds or more funds due to any fundraising activity). Specify all donors approached, especially if negotiations concluded positively.

- 3.2 Implementation capacity: did you face any financial challenges to implementation? If so, what impact did this have on your plans? (Max. 200 words)

Keep the financing/co-financing boxes

**Comment by IronRunes** [comment]
done
