### ISSUE TITLE
Grants and ICs tagging issue 

### ISSUE THREAD

**Issue by ghost** [level73/membernet#188]
Issues with tagging members, this has happened a couple of times where when first created they are tagged but after checking later they have not gone through.   

This is an example of this case where we had to retag them.                                                                                    https://mnet-dev.landcoalition.org/manage/institutionalcontract/145

**Comment by IronRunes** [comment]
@kravinthiren could you be more specific, as in which members did not get correctly tagged? or was it all of them? And in which step of the IC creation did this happen (main org signing the contract or the second step, the meta layer?)
thanks

**Comment by ghost** [comment]
@IronRunes none of them, I tag it initially when creating the ICs and Grants and it save it. However after we go back and check it it does not show up and then we need to retag them.

**Comment by IronRunes** [comment]
so this only happens in ICs and Grants? @kravinthiren

**Comment by IronRunes** [comment]
i just tested this locally and everything went through fine. could you let me know if and when this happens again, along with the data you want to input? (do this via email please)

**Comment by ghost** [comment]
?Will do, it happens sporadically.


Thank you for checking on it.


Best regards,

?

Krishna Ravinthiren
________________________________
