### ISSUE TITLE
Account Request

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#19]
Make sure that new users have a means of requesting an account. 
Flow: 

1.  User fill in a form with 
- username 
- email 
- email confirmation 
- password 
- password confirmation
- member organisation
2. System registers the request, sets user as "inactive"
3. System generates a notification for User managers
4. User managers switch user profile to "active"
5. System notifies the User via email

**Comment by IronRunes** [comment]
@decasadecasa re: bullet point 3, how would we want to go about this? Possibly this could shoot an email, or generate a notification of some other nature. 
At this point, I think we'd need a proper email address for membernet management. :)

**Comment by decasadecasa** [comment]
@IronRunes Great idea about the email, how could we go about setting that up? Should we make it a landcoalition email or gmail? Are there implications for that?

I think a notification within the system would be better than an email (although also having an email would be a good back up) as those can get buried and forgotten about, if it were a notification in system it would be nice if it remained visible until it gets resolved. Not sure how complicated this would be from your end, so open to any suggestions.

**Comment by IronRunes** [comment]
I think the email for the time being is the way to go. 
Notifications are great, I agree, but managing a system where there are tasks to be addressed, a status registry for said tasks, an unclear map of who is responsible for what can lead to a lot more confusion than it could possibly address. 
I suggest we set up a gmail account (landcoalition.info - maybe we already have one), as we know about the limitations of the landcoalition emails in terms of spam filters and the likes. 

Let me know when we have that set up, as this is pretty much ready to go.

**Comment by decasadecasa** [comment]
we have membernet@landcoalition.info, should we make a different one with gmail? im not sure how this one was set up

**Comment by IronRunes** [comment]
@decasadecasa let's just make sure you have access to that, and let's document the process accordingly. at that point we can run a couple of tests. :)

**Comment by decasadecasa** [comment]
we have access. do you need anything else from my side at this point?

**Comment by IronRunes** [comment]
one thing: I'll test the submission of a new account request. be on the lookout for the email coming in to that inbox and let me know if that happens. :)

**Comment by IronRunes** [comment]
@decasadecasa  request sent.

**Comment by decasadecasa** [comment]
no email so far

**Comment by decasadecasa** [comment]
got it, but went to spam

**Comment by decasadecasa** [comment]
the link takes me to the login page

**Comment by IronRunes** [comment]
even if you're logged in already?
mind forwarding the email to me, so I can double check? :)

**Comment by IronRunes** [comment]
thanks for the forward. 
it appears that it redirects to login only if you aren't logged in/your session expired. 
this is pretty much done for now, we'll integrate destination url redirection post-login in another issue. :)

**Comment by decasadecasa** [comment]
this feature is still not working for all staff, as reported by the RCU in LAC. We had to use a gmail for Zulema burneo, as her work email is linked to the generic LAC account. But we did not get any request in the mnet email. 

the email linked to the requested account is zburneo@gmail.com 
please see if you can assist with this

**Comment by IronRunes** [comment]
This has been fixed. 
The postfix server had to be recalibrated to cope with the internal IFAD rules. That lead to an unexpected conflict with the landcoalition.info  email domain, thus making it so that the server would capture the emails going to landcoalition.info instead of forwarding them to the correct destination.
