### ISSUE TITLE
member profiles: member participates in/leads grants section not working accurately 

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#195]
in member pages, in the memeber's work with ILC Section- after having split into leading/participating sections, the grouping of the information is sometimes incorrect. 

For example, in ELCI's profile grant CJA 1501 is displaying under _participates in_, although it should be leading. could you please look into this? 

also, we need the lists to be chronological (newest on top) for both sections.

Thanks

**Comment by IronRunes** [comment]
@decasadecasa This happens because ELCI is set to be **BOTH** the grantee **AND** a participant in the grant. 
The system therefor displays the grant in both lists (you can check it by expanding the grant list in ELCI's profile page or in the backend accessing the grant). 

I'll look into sorting the grants chronologically.

**Comment by decasadecasa** [comment]
@IronRunes we have tagged all things as such, in all grants/ics we tag the lead member as also participating, but it doesnt seem that this is teh case for all entries- or am i mistaken?

**Comment by IronRunes** [comment]
@decasadecasa  it is in this case - if you have other examples where this happens even if the data isn't there to justify it I can look into those to see what it is that isn't working. 

grants are now sorted by start date in both lists.

**Comment by IronRunes** [comment]
I can confirm that all grants that this member leads are also in the participating list. If this is consistent, as you just mentioned, it makes sense.

**Comment by decasadecasa** [comment]
@IronRunes can you remind me of what needs to happen and by whom to push this along? should we start untagging or there is work that you need to still do with dev society?
