### ISSUE TITLE
ICs back-end: No "type" field

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#198]
In the back-end for grants, we have a "type" field, but we dont have this for ICs. 
Would it be possible to add it, and if so, could it be done in a way which doesnt make a blank field display for all the past ones? we dont want to have to go back and indicate the type for all past ones.

Thanks

**Comment by IronRunes** [comment]
We don't have it because we didn"t need it. What donwe want to achieve with this additional field? Right now, the system prepends the particle "IC" to all contracts, as opposed to the relevant type for grants.
