### ISSUE TITLE
Deleting Entries in Manage entities

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#2]
Often the delete button is unresponsive/displays error message & entry does not get deleted OR gets deleted but without confirmation message (and this takes a while to update in results)

**Comment by IronRunes** [comment]
Hey @decasadecasa , could you please elaborate on the "error message" you report? A screenshot would be helpful (on slack). 
Also what exactly do you mean when you say it's unresponsive? 
Thanks

**Comment by decasadecasa** [comment]
unfortunately I can't locate the screenshot I had taken and it is not an issue that happened with each attempt. Perhaps it got resolved with your updates and should it happen again, i'll send over a screenshot. Apologies

**Comment by IronRunes** [comment]
Ok, I updated the labels, but we'll keep the issue open in case this happens and we can document it

**Comment by exhej11** [comment]
![error delete](https://user-images.githubusercontent.com/48788375/55803395-87400180-5ada-11e9-8d45-8753e495f82b.PNG)
Was trying to delete an entry (duplicate organisation) and I received the error that @decasadecasa issued.
