### ISSUE TITLE
FindMe - EMENA

### ISSUE THREAD

**Issue by ghost** [level73/membernet#201]
ACAD contacts on FindMe and others by default go to Puerto Rico when it should be Palestine. 

Unable to save the Alternate Focal Point selection - 
https://findme.landcoalition.org/contacts/member/16362
https://findme.landcoalition.org/contacts/member/17276
https://findme.landcoalition.org/contacts/member/173

Unable to chain the country to Palestine and save the Alternate Focal Point selection
https://findme.landcoalition.org/contacts/member/16370

**Comment by decasadecasa** [comment]
Prior to move off the development server, Findme was communicating and synching wtih mnet. it is no longer doing so, and the back-end tick boxes for roles do not save (although they do on the front end)
