### ISSUE TITLE
ONETEAM page latest contracts not pulling through

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#204]
on the prod sever, we see IC 2011 OXFAM top of the list for latest contracts while on dev server its NES 2002 CONGCOOP. Please assure they update.

**Comment by IronRunes** [comment]
has this been uploaded to prod? the databases do NOT align. it is a one time thing.

**Comment by decasadecasa** [comment]
ok, will you do a final sync to catch anything that went through the cracks or if thats not how it works can you give me the date that you moved it off prod so i can track what needs to be transferred? thanks

**Comment by IronRunes** [comment]
i would really want to avoid doing the sync again, as it is the most cumbersome of the tasks in the migration. 
I'll double check the date and let you know
