### ISSUE TITLE
How big is the file upload limit/did it get reversed with switch to prod?

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#205]
can you please inform us how big the size upload limit is? we couldnt upload a file that was 11mb and wondering if it is the size or something else. Would it be possible to increase the size, should that be the case?

**Comment by IronRunes** [comment]
Limit is 24mb, 20 files at a time. Issue might be with something else, i.e. file mime type (.doc, .xls and the likes). there are some limitations for mime types for security reasons. 
let me know.
