### ISSUE TITLE
Can't delete duplicate org/redirects to mnet.org not able to handle request

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#206]
There might be 2 issues here, not sure- but we need to delete a duplicate of LAND PORTAL org (#243). When we try, we get the following message, which looks different to the other types of internal error messages. I checked and we do have a user connected to org 243, but they are already dis-activated. Could you look into this? Thanks

![Capture](https://user-images.githubusercontent.com/40179449/82536428-bc75aa80-9b48-11ea-82b2-e68e6423b04c.PNG)

**Comment by IronRunes** [comment]
@decasadecasa there is an institutional contract attached to org id 243 that is blocking this.

**Comment by IronRunes** [comment]
namely, IC code 1503
