### ISSUE TITLE
Member Profiles via the Search tab

### ISSUE THREAD

**Issue by ghost** [level73/membernet#207]
When searching for organizations using the 'Search' tab they do not show up.

<img width="789" alt="Screen Shot 2020-05-21 at 10 56 06 AM" src="https://user-images.githubusercontent.com/60397500/82543444-d5378d80-9b53-11ea-954c-3c240509deca.png">

**Comment by IronRunes** [comment]
this works fine as long as organisations have a connected Member Profile. In the case of the two orgs above the member profiles do not exist.

**Comment by ghost** [comment]
They appear to be listed as orgs. 

<img width="1440" alt="Screen Shot 2020-05-27 at 7 09 39 PM" src="https://user-images.githubusercontent.com/60397500/83051107-cf5b1400-a04d-11ea-93a6-bca3e0df0796.png">
<img width="1440" alt="Screen Shot 2020-05-27 at 7 09 56 PM" src="https://user-images.githubusercontent.com/60397500/83051118-d5e98b80-a04d-11ea-92e0-6fdda62e449d.png">

**Comment by IronRunes** [comment]
@kravinthiren they **MUST** have a member profile attached to show up in the search results correctly.
