### ISSUE TITLE
Every user can give permission to itself to edit every sections. 

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#21]
Once you are a user and have access to only one section you can access all the sections afterwards. Only particular people should have the authority to grant permission to other users.

**Comment by IronRunes** [comment]
could you elaborate? 
what do you mean by "access to one section"?

**Comment by exhej11** [comment]
When you gain access to managing users you can give access to your account or any other account to manage everything, even entities that the authorized person (in this case @decasadecasa ) did not give you permission to manage.

**Comment by IronRunes** [comment]
so we want to add a layer of permissions to set permissions? An extra checkbox with "Assign Permissions" would do?

**Comment by exhej11** [comment]
I think that would work fine and avoid risks of giving unlimited freedom to every user. 
@decasadecasa please confirm.
