### ISSUE TITLE
Hide travels from everyone except staff

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#215]
please hide the travels in:
-member profiles (see if you can reformat the padding and the like to fill the space on the page somehow)
-search function
-anywhere else where they might be for all to access (should only remain for oneteam)

**Comment by IronRunes** [comment]
- travels are already hidden in member profile, not available to no one
- removed from the search function for members only
- removed from the dashboard for members only

please check on DEV and let me know

**Comment by decasadecasa** [comment]
awesome, thanks
