### ISSUE TITLE
Membership 2021

### ISSUE THREAD

**Issue by ghost** [level73/membernet#218]
I did change the membership status from 'Yes' to 'No' for 2021 membership fees paid for members. However it changed back after checking it again. I would not want to duplicate my efforts to change it again if I have to change it again later.

**Comment by IronRunes** [comment]
let me understand this better.
1. you changed the status to No from Yes for members (assuming it was a mistake in the first place). Did this work? 
2. you want to revert it to Yes now, and it isn't saving?

**Comment by ghost** [comment]
No, it was in an error set to Yes from No following the migration by default to all members for 2021.
Manually each member was individually changed to No, and when I went back to update 2020 membership fees paid for members I realized the manual change did not work.

Thanks,

Krishna Ravinthiren



On Jun 18, 2020, at 3:23 PM, Alan Zard <notifications@github.com<mailto:notifications@github.com>> wrote:



let me understand this better.

  1.  you changed the status to No from Yes for members (assuming it was a mistake in the first place). Did this work?
  2.  you want to revert it to Yes now, and it isn't saving?

**Comment by IronRunes** [comment]
I just changed ACME to all 3 different statuses and back again, had no problem
To speed things up, if you have a list of member IDs that need this to be addressed, I can automate the process

**Comment by ghost** [comment]
Yes it did work at first but then it didn’t once I checked later.

It is actually the entire membership for 2021. There are a very few that need to be changed to Yes for the very few that need to be changed I can change them back later.

Thanks,

Krishna Ravinthiren

On Jun 18, 2020, at 16:26, Alan Zard <notifications@github.com> wrote:

﻿

I just changed ACME to all 3 different statuses and back again, had no problem
To speed things up, if you have a list of member IDs that need this to be addressed, I can automate the process
