### ISSUE TITLE
Organization error in PUP when saving contacts

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#22]
![PUP Error](https://user-images.githubusercontent.com/48788375/55411559-26f31200-5566-11e9-8728-b425eda05e71.PNG)
![PUP ERROR 2](https://user-images.githubusercontent.com/48788375/55411565-28243f00-5566-11e9-92d0-d0094279e46f.PNG)
 When searching for an organization it doesn't appear. Trying to create a new one under the name that did not appear gives this error message.

**Comment by IronRunes** [comment]
That org exists, but has no full name for it - thus generating the failed finding. I'll add the name to the DB so it will pop up

**Comment by IronRunes** [comment]
Fixed

**Comment by decasadecasa** [comment]
@IronRunes How do we prevent this happening again? Where does the full name need to be saved in order for it to appear? Thanks

**Comment by IronRunes** [comment]
there are no more orgs without a name in the DB. that was the only case. the only place where one can create an org now is in the Add Non-Member Contact page.

**Comment by decasadecasa** [comment]
Great, thanks
