### ISSUE TITLE
Contacts not being deleted

### ISSUE THREAD

**Issue by ghost** [level73/membernet#223]
Contacts are not being deleted on FindMe despite deleting them on MemberNet and vice versa.

**Comment by decasadecasa** [comment]
@IronRunes Contact adding and editing seem to work. I understand that the deletion is not synched from mnet to findme- but should it not be so from findme to mnet? we really need to outline the sync rules clearly

**Comment by IronRunes** [comment]
Delete is never synced, currently. We can set it up to be one-directional, if there are no unwanted consequences we can think of (as in, no occasion in which we need a contact to be in mnet and not in findme)

**Comment by decasadecasa** [comment]
@IronRunes Thanks. The only case in which we would need contacts to be in mnet and not findme is for staff, but that is a limited list. Therefore, we could make it one directional for deletion from Findme to Mnet.

**Comment by ghost** [comment]
When I updated ICCA Consortium's contacts, the deletion from FindMe were not reflected on MemberNet and I had to do it on MemberNet to update their profile.
