### ISSUE TITLE
Searching a contact which is already saved and nothing shows up. 

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#23]
![error pup](https://user-images.githubusercontent.com/48788375/55464862-49d00580-55fc-11e9-9bd7-9f39d8eb3072.PNG)

When creating a new one with the same data it shows that is a duplicate and this contact already exist. When  searching again the system shows only the latest one which I force saved. Meaning that is a duplicate, but the old one still doesn't show.

**Comment by IronRunes** [comment]
ok, found the issue. we have a few contacts that have a missing value in the db. I'll create a new issue with this, and close the current issue, but maybe we need an extra filter for the two different platforms as well.
