### ISSUE TITLE
Pop up verification box to avoid Double-counting (M&E Reps)

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#232]

**Comment by decasadecasa** [comment]
@IronRunes Could you add the metadata field "year changes took place" under changes in policies & practices to feed the line of text you inserted ?

**Comment by decasadecasa** [comment]
also, the confirmation of previous figures is also pulling into the current report (i got this prompt even though this is the first report we have for the platform)
![confirm_figures](https://user-images.githubusercontent.com/40179449/96256443-fa241580-0fb8-11eb-9bf7-fc4bebaf3bc8.PNG)
