### ISSUE TITLE
text editor in nes and cbi reports: make all links open in new tab

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#240]
the box you inserted for making urls open in a new tab doesnt work, it is unclickable. is it possible to directly make all links open in new tabs, as we would want this for all links.... and in fact for all links on the platform as a whole as mentioned before

**Comment by IronRunes** [comment]
that is an issue with the plugin we use for the RTE, I'll track it down and see if they've released a fix. 
in the meantime, links now inherently are opened in a new window (no need to click on the checkbox)
