### ISSUE TITLE
FindMe not differentiating between all member and non member organizations in results

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#38]
When searching contacts, the system doesn't register all member organizations as such.

For example, the contact of Amina Amharech from AZUL (new member since 2018-maybe this is the problem?), only shows up as a general contact, despite AZUL being a member (0 results when searching for member contacts only).

**Comment by IronRunes** [comment]
We need to switch the contact from being a general contact to a member contact. 
We have a bunch of contacts that were input into the platform before having the association in place between FindMe and Membernet. This means that, by the means of the interface, those contacts are considered general contacts.

**Comment by IronRunes** [comment]
addressed in the big sync ran yesterday
