### ISSUE TITLE
Last 10 section in ILC profiles - all entities in section do not update properly

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#4]

**Comment by IronRunes** [comment]
Hey @decasadecasa , could you elaborate please? what do you mean with "do not update properly"?

**Comment by decasadecasa** [comment]
Afternoon @IronRunes, I mean that the most recent entries are not visible in the preview list, if you look at governance events for example, it's showing the events from 2013-16 where there have been more recent ones. Also travels, do not see the entries of the ones that have been recently uploaded. I hope this helps!

**Comment by IronRunes** [comment]
hey there, the current state gets the latest 10 objects in entities sorted by the **date of last modification**.
this means that if an older object gets amended or updated, it will show up at the top of the list. 

we can either change this to sort by **date of creation** of the object, or keep the behavior like it is and change the wording on the page.

**Comment by decasadecasa** [comment]
Hi there! Thanks for figuring this out. 
While i think it would be good to have some kind of indicator for what has been updated, i think in this section its better to go by **date of creation**. Would you agree? 

Perhaps later we can explore other options for indicating to our users when something has been updated, as with the notifications system (forget if this was feasible or not).

**Comment by IronRunes** [comment]
@decasadecasa this should be ok now

**Comment by decasadecasa** [comment]
I see the information is organizing by date of creation , but now I realize what I actually meant was to have it display in the list chronologically (or alphabetically) according to how it was **tagged** and not just uploaded (the actual latest 10 irrespective of when it was uploaded/modified). Would this be possible? Listing by creation works for most cases but I didn't consider that we would have recently uploaded events from 2003 for example.  

If not possible (and in any case) I'll draft some text that explains how it works as otherwise can be quite confusing. If we can't organize the dates in the column chronologically or the titles alphabetically in addition to the creation date, then perhaps it is actually better to keep it going by date modified with an explanation. So sorry for the complications! 

![Capture](https://user-images.githubusercontent.com/40179449/55165209-4d333f00-516d-11e9-83fc-dde03ad73e4a.PNG)

**Comment by IronRunes** [comment]
that can be done. 
I can use years for things like reports and events, should I use the "start of activity" year or the "end of activity" year for things like travels, contracts and contributions?

**Comment by decasadecasa** [comment]
Great! I think start of activity, unless there are repercussions I can't foresee?

**Comment by IronRunes** [comment]
this is done!

**Comment by IronRunes** [comment]
Can we close this one?

**Comment by decasadecasa** [comment]
yes, thanks!
