### ISSUE TITLE
When searching contacts from ''Regional Steering Committee'' nothing shows up.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#40]
![rc](https://user-images.githubusercontent.com/48788375/55712170-8e89e100-59ee-11e9-9a82-7fda2fba4118.PNG)
![0](https://user-images.githubusercontent.com/48788375/55712181-95185880-59ee-11e9-8d91-f1f688df4616.PNG)

While searching by a particular name, the registered contact shows up but the assigned role "Regional Steering Comittee'' doesn't .
![va](https://user-images.githubusercontent.com/48788375/55712422-ff30fd80-59ee-11e9-9b13-588ae1370598.PNG)

**Comment by exhej11** [comment]
It is the same case with the ''Council Representative'' filter.

**Comment by decasadecasa** [comment]
''Council Representative'' filter experiencing same issue

**Comment by IronRunes** [comment]
fixed
