### ISSUE TITLE
Separate EMENA from Global results in membership fees

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#42]
Currently there is no option for viewing EMENA membership fees only (i presume they are grouped under global?). We'd like to separate them.

**Comment by IronRunes** [comment]
if you search for EMENA as a region, you get the membership fee results - could you clarify the issue?

**Comment by decasadecasa** [comment]
Its not the case that something isnt working, its just that in the general membership fees section under ILC profiles, it appears as thought EMENA is grouped under "global" and we'd like it to be distinguished in metrics as are the other regions. 
![Capture](https://user-images.githubusercontent.com/40179449/56644103-4ff55700-667b-11e9-9691-96a848f6acd4.PNG)

**Comment by IronRunes** [comment]
hard refresh and everything should be ok

**Comment by exhej11** [comment]
Is it possible to include it also in the graph on the left as a separate line?
![Capture](https://user-images.githubusercontent.com/48788375/56660175-441b8c00-669f-11e9-9160-a7bbc2bed2c7.PNG)

**Comment by IronRunes** [comment]
hard refresh should fix that. i addressed it along with the entry on the percentages. let me know if it doesn't work

**Comment by exhej11** [comment]
The percentages were fixed immediately that's why I didn't do a hard refresh. After it also the graph line appeared.
