### ISSUE TITLE
Change the indication in the membership fee from red box with an ''x'' to a yellow box with ''-'' for the years that the member hasn't been part of ILC.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#43]
PWESCR example
![55956370-1af10980-5c64-11e9-832d-2221af44a983](https://user-images.githubusercontent.com/48788375/56022965-21878b80-5d0d-11e9-9fbe-8db19baa6e6c.PNG)
Searching it in the ''Search page indicated it correctly while in the Member's profile page it is shown with red box ''x''
![pwescr](https://user-images.githubusercontent.com/48788375/56023008-3bc16980-5d0d-11e9-9d76-c812290264e5.PNG)

**Comment by exhej11** [comment]
Another option can be to show from the year that the Member has been part of ILC if it is possible.

**Comment by IronRunes** [comment]
fixed
