### ISSUE TITLE
Cannot delete contacts from Membernet

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#46]
![Capture](https://user-images.githubusercontent.com/48788375/56718200-9c559b00-673e-11e9-9e40-3b7ef31850fb.PNG)

![11](https://user-images.githubusercontent.com/48788375/56718112-703a1a00-673e-11e9-9c1d-14461219c2b1.PNG)
(The ones that have become duplicates)

**Comment by IronRunes** [comment]
what account are you using?

**Comment by exhej11** [comment]
username: exhej11
email: e.gjoka@landcoaltion.org

**Comment by IronRunes** [comment]
mind trying this again? it should be fixed.

**Comment by exhej11** [comment]
Fixed, it worked.
