### ISSUE TITLE
Add ''Secondary email'' field in Membernet and ''Add member contact'' section in FindMe when adding a contact.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#48]

**Comment by IronRunes** [comment]
How do you mean? Contacts are either member contacts or they are not. Why would we want to mix this up on Membernet - as well as on FindMe?

**Comment by exhej11** [comment]
I mean adding an option to insert a second email for member contacts in FindMe as the option doesn't exist as well as in Membernet
![Capture](https://user-images.githubusercontent.com/48788375/56789881-4696f680-6803-11e9-9709-1da38b33a9f2.PNG)
FindMe
![Cap1ture](https://user-images.githubusercontent.com/48788375/56789889-4bf44100-6803-11e9-95ec-5f47857dcc36.PNG)
Why have 2 entries for the same person when it can be saved once with 2 emails below.
Alot of the business cards that we receive have 2 emails.

**Comment by IronRunes** [comment]
how would we want to manage that within Mailchimp? Mailchimp creates user accounts based on the email, so 1 email = 1 person. We purposedely removed the secondary email registration as it didn't make that much sense to have multiple emails for contacts/newsletters. we would need to sync this with Comms, I think

**Comment by decasadecasa** [comment]
Since this has repercussions on that level, lets stick to one email entry then. But could we find a solution for the double/triple contacts appearing? thanks
