### ISSUE TITLE
For Filtered searches such as Steering Committee and Council Representative the yielded results are successful but when you want to edit a contact it seems that it doesn't have the role assigned

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#49]
![yr](https://user-images.githubusercontent.com/48788375/56889614-22dbe680-6a77-11e9-93e9-4a7c04a886ca.PNG)
![e](https://user-images.githubusercontent.com/48788375/56889616-24a5aa00-6a77-11e9-9095-66727a5dcac7.PNG)

**Comment by IronRunes** [comment]
fixed
