### ISSUE TITLE
When creating a new contact and filtering the search by organization, the latest created contact doesn't show up.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#50]
![testt](https://user-images.githubusercontent.com/48788375/56890400-a0085b00-6a79-11e9-99ca-969a0449d658.PNG)
(I created a test contact and it only displayed the previous 2 that were already there and not the new one)

**Comment by IronRunes** [comment]
what type of contact have you created? member or not member?

**Comment by exhej11** [comment]
Member Contact

**Comment by exhej11** [comment]
Created another one and the issue is still occuring. The latest created contact in this case ''Test One'' does not show up when filtering the search by organization
![aap](https://user-images.githubusercontent.com/48788375/57215553-8624c600-6fed-11e9-9419-3f023b559b15.PNG)
While searching with the contacts name works
![to](https://user-images.githubusercontent.com/48788375/57215566-92a91e80-6fed-11e9-8d60-b29027306aab.PNG)

I am leaving the contact there in order for you to check what the issue is with it and I am not deleting it this time.

**Comment by IronRunes** [comment]
merge findme org list and member list from mnet into the org dropdown
hide member orgs from findme list
make sure that there is a distinction in the vars that are sent over to perform search against different fields
