### ISSUE TITLE
When I created a test contact in FindMe, it created duplicates in Membernet

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#51]
![atest](https://user-images.githubusercontent.com/48788375/56890583-26bd3800-6a7a-11e9-8ef5-7d3d5c6e141e.PNG)

**Comment by IronRunes** [comment]
I just did this and it worked fine. Any particular flags you were using in this instance? (i.e. roles, newsletters, etc.)?

**Comment by exhej11** [comment]
Not really, no roles or newsletters. Anyways we can close this one and if it becomes a repetitive issue we can reopen it.
