### ISSUE TITLE
Search functions: selected filters text not displayed upon loading of results

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#56]
When conducting a search in any of the search functions, after the results are loaded the selected filters clear (the text indicating which results are displaying based on the chosen filters is empty). We would like to keep the searched "text" in the search bars so that users can know what data they are viewing.

**Comment by IronRunes** [comment]
done

**Comment by decasadecasa** [comment]
Could we do this for the M&E search as well please? Thanks

**Comment by IronRunes** [comment]
done
