### ISSUE TITLE
Cannot delete an organisation

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#71]
![del](https://user-images.githubusercontent.com/48788375/59094898-79123400-8917-11e9-9b8a-af88723f2338.PNG)

**Comment by IronRunes** [comment]
This can happen for a number of reasons. 
1. The Org already has a bunch of records from other entities connected to it (grants, travels, whatever). This would block the deletion. 
2. Same goes with a Membership Profile and membership fees. 
It would help to understand which organisation is raising the issue @exhej11
