### ISSUE TITLE
When you save a entry in Manage NES/CBI Reports it shows a long message of background data and it does not allow you to access the resource page to upload a file.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#78]
After multiple times of trying to save it and enter the resource page, the platform saved them as seperate files and duplicated them.
 And only after pressing the edit button it gives access to save it and to open the resource page.
![bug](https://user-images.githubusercontent.com/48788375/60960824-198ab800-a30b-11e9-860a-95fe4f106cdc.PNG)
![12345](https://user-images.githubusercontent.com/48788375/60960831-1bed1200-a30b-11e9-9c10-8814be657135.PNG)
![b1](https://user-images.githubusercontent.com/48788375/60960835-20192f80-a30b-11e9-8c18-86f44ee7f739.PNG)

**Comment by IronRunes** [comment]
fixed!
