### ISSUE TITLE
No alphabetical or chronological hierarchy in search results

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#8]
In Search section is not possible searching based on a specific alphabetical (organization) or chronological rule (grants, travels, IC,good practices, events, contributions)

**Comment by IronRunes** [comment]
@exhej11 @decasadecasa this has been addressed, contents of the search results are now sorted by descending year

**Comment by decasadecasa** [comment]
@IronRunes Great! thank you so much. Before we close the issue, could I ask you to make the organizations and membership fees (selected in the side bar)  appear alphabetically when doing a general search (just leaving the fields blank and pressing search)?

**Comment by IronRunes** [comment]
@decasadecasa let me get this straight. :)
**ONLY** in the case that a full search is requested
**THEN** 
-- **ONLY** for Organisations and Membership fees
--- We want alphabetically sorted results, **ignoring the year sorting**

Is that correct? 

If it is, I suggest we close this issue and create a new one with the appropriate priority rating. :)

**Comment by decasadecasa** [comment]
yes, thats what i meant :) thanks, will create a new entry
