### ISSUE TITLE
Log in page: Update number of members and countries

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#82]
Please change # of members from 271 to **256** and countries from 78 to **79**

**Comment by decasadecasa** [comment]
**Furthermore, please:**
- remove the logos of the members that appear on the picture. They are distracting and hard to read. 
- Increase the size of the Mnet logo at the top
-decrease bottom banner width
-align banner text & logos in a more aesthetically pleasing way (text now running on many lines with no alignment)

**Comment by IronRunes** [comment]
done
