### ISSUE TITLE
Is there a limitation for the number of letters or words in specific fields in Membernet?

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#84]
I could not save an entry and as soon as I deleted a relatively long 'Author' field the entry was saved.
If there is a limitation can we remove it?
![cant create entry](https://user-images.githubusercontent.com/48788375/61940950-bf3e5800-af96-11e9-94b2-66d1d9315cb2.PNG)

**Comment by IronRunes** [comment]
this is fixed.
