### ISSUE TITLE
Some elements on landing page map not displaying full info

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#93]
See picture below. Upon clicking on dot, only title displays. Missing data 
![Capture](https://user-images.githubusercontent.com/40179449/63846714-9ee62c80-c98c-11e9-99f0-ddd261c2742c.JPG)

**Comment by IronRunes** [comment]
hey @decasadecasa it looks like the main issue with this specific case is that we don't have a NES Focal Point for the hosting Org. that kind of breaks up everything else.

**Comment by decasadecasa** [comment]
Hi @IronRunes, I think we do, at least on the NES facilitators list there is the following: 

NES Tanzania | Mr Bernard P.Baha | TALA | bernard.baha@gmail.com
I know thisi s not the host organization focal point, but thats why we have the "hosted by" section linking the member. 

How can we proceed?

**Comment by decasadecasa** [comment]
Also, there are hardly any focal points for CBIs displayed in the pop ups, can you tell me what this is caused by? thanks

**Comment by IronRunes** [comment]
The roles "NES Focal Point" and "CBI Focal Point" for hosting orgs is what the system looks for to populate those fields. If the Org that receives the grant has no NES focal point (or CBI Focal Point), then it shows nothing.

**Comment by IronRunes** [comment]
I did fix the issue of not showing anything at all, by the way.

**Comment by decasadecasa** [comment]
Ok, so these contacts would have to be tagged accordingly through FindMe>?

**Comment by IronRunes** [comment]
> Ok, so these contacts would have to be tagged accordingly through FindMe>?

yup, that should do it
