### ISSUE TITLE
hierarchy in nes/cbi contacts on landing page

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#94]
could we please have the list of facilitators be organised alphabetically for NES contacts? ie, NES Albania, NES Bolivia, Colombia etc.? 
![Capture](https://user-images.githubusercontent.com/40179449/63942830-c281a380-ca6e-11e9-9ab4-5c859479c837.JPG)

Same for CBI

**Comment by IronRunes** [comment]
done
