### ISSUE TITLE
Landing page platforms map: add work areas

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#96]
Please furthermore pull the work areas onto the pop ups that display upon opening a nes or cbi on the map, and link them to the M&E work area pages. 

Also, could you make the grey box a bit darker/the font a bit thicker as its slightly difficult to read ?

many thanks!

**Comment by IronRunes** [comment]
this is already happening for CBIs. Check CBI WIDGRA (active in South Africa, for example). 
I can extend this for NES as well, although it will always be linked to the "Multi-stakeholder platform" initiative. 
let me know. :)

**Comment by decasadecasa** [comment]
sorry, i got confused with feedback suggestions from colleagues.  please link the NES to multistakeholder initative page. thanks
