### ISSUE TITLE
cant delete a duplicate in manage organisations

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#98]
we have a duplicate entry in manage organisations for land portal, and i cant delete either one. could you please look nto this? thanks

**Comment by IronRunes** [comment]
both have bits and bobs attached to them (in the form of contracts, grants, travels, etc). 
currently, the "active" one is the one with ID 376, so the on with ID 243 can be deleted. But to do that, you need to make sure that any content connected to the 243 org is successfully migrated to the 376 org. 
I'd suggest renaming the 243 entry to something like [TO REMOVE] Land Portal, so it can be easier to find and see it where it is popping up.
let me know if you need any help with this.
